import os
import math
from collections import defaultdict
from ff_data import *

# GROMACS inputs/outputs
def parse_gro(filename):
    with open(filename) as f:
        lines = f.readlines()
    title  = lines[0].rstrip("\n")
    nbeads = int(lines[1].strip())
    beads  = []
    
    # Auto-detect column width from first atom line
    first = lines[2]
    # Find the two decimal points in the coordinate region (after col 20)
    coord_region = first[20:]
    dot1 = coord_region.index('.')
    dot2 = coord_region.index('.', dot1 + 1)
    col_width = dot2 - dot1  # distance between decimal points = n+5
    
    for line in lines[2:2 + nbeads]:
        c = col_width
        a = dict(
            resnum   = int(line[0:5]),
            resname  = line[5:10].strip(),
            atomname = line[10:15].strip(),
            atomnum  = int(line[15:20]),
            x = float(line[20:20+c]),
            y = float(line[20+c:20+2*c]),
            z = float(line[20+2*c:20+3*c]),
        )
        if len(line.rstrip()) > 20 + 3*c:
            try:
                vc = c - 1  # velocity width is n+4 (one fewer than position)
                a['vx'] = float(line[20+3*c:20+3*c+vc])
                a['vy'] = float(line[20+3*c+vc:20+3*c+2*vc])
                a['vz'] = float(line[20+3*c+2*vc:20+3*c+3*vc])
            except (ValueError, IndexError):
                pass
        beads.append(a)
    box = tuple(float(v) for v in lines[2 + nbeads].split()[:3])
    return title, beads, box


def write_gro(filename, title, beads, box):
    """Write a GROMACS .gro file. Atom/residue numbers wrap at 99999."""
    with open(filename, "w") as f:
        f.write(title + "\n")
        f.write(f"{len(beads):5d}\n")
        for i, a in enumerate(beads, 1):
            rn = a['resnum'] % 100000
            an = i % 100000
            if 'vx' in a:
                f.write(
                    f"{rn:5d}{a['resname']:<5s}{a['atomname']:>5s}{an:5d}"
                    f"{a['x']:8.3f}{a['y']:8.3f}{a['z']:8.3f}"
                    f"{a['vx']:8.4f}{a['vy']:8.4f}{a['vz']:8.4f}\n"
                )
            else:
                f.write(
                    f"{rn:5d}{a['resname']:<5s}{a['atomname']:>5s}{an:5d}"
                    f"{a['x']:8.3f}{a['y']:8.3f}{a['z']:8.3f}\n"
                )
        f.write(f"  {box[0]:.5f}  {box[1]:.5f}  {box[2]:.5f}\n")

# Molecule topology writers


def write_gra_itp(filename, resname, beads, bonds, angles, b,
                  kb=3800.0, ka=200.0, planar_kd=50.0, use_planar_dihedral=True):
 
    # Build adjacency for planar dihedral generation
    # For each bead i with neighbours [j, k, l], write improper i-j-k-l
    adj = {}
    if use_planar_dihedral:
        from collections import defaultdict
        _adj = defaultdict(list)
        for (a_, b_) in bonds:
            _adj[a_].append(b_)
            _adj[b_].append(a_)
        adj = dict(_adj)
 
    with open(filename, 'w') as f:
        f.write("; MARTINI v2 graphene sheet topology\n")
        f.write("; Generated by gen_sys.py\n")
        f.write(f"; {len(beads)} beads/layer | b0={b:.4f} nm | kb={kb:.1f} | ka={ka:.1f}\n")
        f.write(f"; planar_dihedral={'ON (equilibration only)' if use_planar_dihedral else 'OFF (production)'}\n\n")
 
        # --- moleculetype ---
        f.write("[ moleculetype ]\n")
        f.write("; name  nrexcl\n")
        f.write(f"  {resname}  2\n\n")
        # nrexcl=2: exclude 1-2, 1-3, 1-4 within the aromatic sheet
 
        # --- atoms ---
        f.write("[ atoms ]\n")
        f.write("; nr   type  resnr  resname  atom     cgnr  charge  mass\n")
        for a in beads:
            f.write(f"  {a['atomnum']:<5d} C1    1     {resname:<5s}"
                    f"  {a['atomname']:<7s}  {a['atomnum']:<5d}  0.0   36.0\n")
        # mass 36 g/mol: each CG bead represents ~3 carbons (3 × 12 = 36)
 
        # --- bonds ---
        f.write("\n[ bonds ]\n")
        f.write("; i      j      funct  b0(nm)   kb(kJ/mol/nm²)\n")
        for (i, j) in bonds:
            f.write(f"  {i:<6d} {j:<6d} 1      {b:.4f}   {kb:.1f}\n")
 
        # --- angles ---
        f.write("\n[ angles ]\n")
        f.write("; i      center  k      funct  theta0(deg)  ka(kJ/mol/rad²)\n")
        f.write("; funct=2 = G96/cosine harmonic, standard for MARTINI\n")
        for (i, c, k) in angles:
            f.write(f"  {i:<6d} {c:<6d} {k:<6d} 2      120.0        {ka:.1f}\n")
 
        # --- dihedrals (planar restraint, equilibration only) ---
        if use_planar_dihedral:
            f.write("\n[ dihedrals ]\n")
            f.write("; Improper planar dihedrals — keep sheet flat during equilibration\n")
            f.write("; funct=2: harmonic improper  phi0=0 deg  kd=planar_kd kJ/mol\n")
            f.write("; REMOVE for production runs and any gmx rdf / PBC-sensitive analysis\n")
            f.write("; i      j      k      l      funct  phi0   kd\n")
            written = set()
            for i, nbrs in adj.items():
                if len(nbrs) >= 3:
                    j, k, l = sorted(nbrs)[:3]
                    key = (i, j, k, l)
                    if key not in written:
                        written.add(key)
                        f.write(f"  {i:<6d} {j:<6d} {k:<6d} {l:<6d} 2      0.0    {planar_kd:.1f}\n")
 
        f.write("\n")

# def write_gra_itp(filename, resname, beads, bonds, angles, b):
#     with open(filename, 'w') as f:
#         f.write("; MARTINI v2 graphene sheet topology\n")
#         f.write("; Generated by gen_sys.py\n\n")
#         f.write("[ moleculetype ]\n; name  nrexcl\n")
#         f.write(f"  {resname}  1\n\n")
#         f.write("[ atoms ]\n; nr  type  resnr  resname  atom  cgnr  charge  mass\n")
#         for a in beads:
#             f.write(f"  {a['atomnum']:<5d} C1   1  {resname:<5s}"
#                     f"  {a['atomname']:<7s} {a['atomnum']:<5d}  0.0  36.0\n")
#         f.write("\n[ bonds ]\n; i  j  funct  b0(nm)  kb(kJ/mol/nm^2)\n")
#         for (i, j) in bonds:
#             f.write(f"  {i}  {j}  1  {b:.4f}  3800.0\n")
#         f.write("\n[ angles ]\n; i  j  k  funct  theta0(deg)  ka(kJ/mol/rad^2)\n")
#         for (i, c, k) in angles:
#             f.write(f"  {i}  {c}  {k}  2  120.0  100.0\n")
#         f.write("\n")


def write_mea_itp(filename, resname, beads, bonds, angles, b0):
    n_beads = len(beads)
    with open(filename, 'w') as f:
        f.write(f"; MARTINI v2 MEA lipid chain topology — {resname}\n")
        f.write("; Generated by gen_sys.py\n\n")
        f.write("[ moleculetype ]\n; name  nrexcl\n")
        # nrexcl=1: exclude only directly bonded (1-2) pairs within the chain.
        f.write(f"  {resname}  2\n\n")
        f.write("[ atoms ]\n")
        f.write("; nr  type  resnr  resname  atom  cgnr  charge  mass\n")
        for local_idx, (name, mtype, chg, mass) in enumerate(beads, 1):
            # mtype is now "CGH" for the ghost bead (set in ff_data.LIPID_BEADS)
            # so no override needed — mtype maps directly to forcefield.itp atomtype
            f.write(f"  {local_idx:<3d} {mtype:<5s}  1  {resname:<5s}"
                    f"  {name:<6s} {local_idx:<3d}  {chg:.1f}  {mass:.1f}\n")
        f.write("\n")
        f.write("[ bonds ]\n")
        f.write("; i  j  funct  b0(nm)  kb(kJ/mol/nm^2)\n")
        for idx, (i, j) in enumerate(bonds):
            kb = 3800.0
            f.write(f"  {i}  {j}  1  {b0:.4f}  {kb:.1f}\n")
        f.write("\n")
        f.write("[ angles ]\n")
        f.write("; i  j  k  funct  theta0(deg)  ka(kJ/mol/rad^2)\n")
        f.write("; funct=2 = G96 cosine harmonic; theta0=180 deg for straight chain\n")
        for (i, c, k) in angles:
            f.write(f"  {i}  {c}  {k}  2  180.0  25.0\n")
        f.write("\n")
        f.write("[ exclusions ]\n")
        for j in range(2, n_beads + 1):
            f.write(f"  1  {j}\n")
        f.write("\n")
        f.write("[ position_restraints ]\n")
        f.write("; atom  funct  fcx  fcy  fcz\n")
        f.write(f"  1     1      5000  5000  5000\n\n")

def load_single_odorant(resname):
    ODORANT_DIR = "./inputs/odorants/"
    gro_path = ODORANT_DIR + f"{resname}_c.gro"
    if not os.path.exists(gro_path):
        raise FileNotFoundError(
            f"Odorant .gro not found: {gro_path}\n"
            f"Expected file: inputs/odorants/{resname}.gro"
        )
    _, beads, _ = parse_gro(gro_path)
    cx = sum(b['x'] for b in beads) / len(beads)
    cy = sum(b['y'] for b in beads) / len(beads)
    cz = sum(b['z'] for b in beads) / len(beads)
    for b in beads:
        b['x'] = round(b['x'] - cx, 6)
        b['y'] = round(b['y'] - cy, 6)
        b['z'] = round(b['z'] - cz, 6)

    # Annotate with MARTINI type/charge/mass from the template
    template = ODORANT_TEMPLATES.get(resname, [])
    for b, (name, mtype, chg, mass) in zip(beads, template):
        b['_mtype']  = mtype
        b['_charge'] = chg
        b['_mass']   = mass

    r_eff = max(
        math.sqrt(b['x']**2 + b['y']**2 + b['z']**2) for b in beads
    ) + 0.235
    return beads, r_eff


def load_droplet(resname, lx, ly, z_surface):
    ODORANT_DIR = "./inputs/odorants/"
    gro_path = ODORANT_DIR + f"{resname}_droplet_c.gro"
    if not os.path.exists(gro_path):
        raise FileNotFoundError(
            f"Droplet .gro not found: {gro_path}\n"
            f"Expected: inputs/odorants/{resname}_out.gro"
        )
    _, beads, box = parse_gro(gro_path)
    r_droplet = box[0] / 2.0
    print(f"  Droplet radius (estimated from box): {r_droplet:.3f} nm")
    z_min = min(b['z'] for b in beads)
    x_cen = sum(b['x'] for b in beads) / len(beads)
    y_cen = sum(b['y'] for b in beads) / len(beads)
    dx = lx / 2.0 - x_cen
    dy = ly / 2.0 - y_cen
    dz = z_surface - z_min
    atom_list = []
    for b in beads:
        new = dict(b)
        new['atomnum'] = 0
        new['x'] = round((b['x'] + dx) % lx, 6)
        new['y'] = round((b['y'] + dy) % ly, 6)
        new['z'] = round( b['z'] + dz,       6)
        atom_list.append(new)
    return atom_list, r_droplet

def write_system_top(filename, run_dir, mol_counts, bead_types_used,
                     itp_files, box, odorant_resname=None, is_droplet=False, if_water=False, if_antifreeze=False):
    """Write the master GROMACS topology file.

    Parameters
    ----------
    filename         : output path, e.g. 'run_dir/system.top'
    run_dir          : simulation folder name (for header comment)
    mol_counts       : dict  {resname: count}, e.g. {'GRA':4, 'TMEA':1200, ...}
    bead_types_used  : list of MARTINI type strings (for forcefield.itp)
    itp_files        : list of .itp filenames to #include (molecule topologies)
    box              : (lx, ly, lz) in nm
    odorant_resname  : string or None
    is_droplet       : bool — tags the run type in the header
    """
    run_tag = "droplet" if is_droplet else "vapor"
    od_tag  = odorant_resname if odorant_resname else "none"

    with open(filename, 'w') as f:
        f.write(f"; GROMACS topology — MARTINI hair surface simulation\n")
        f.write(f"; Run folder : {run_dir}\n")
        f.write(f"; Odorant    : {od_tag}  ({run_tag} mode)\n")
        f.write(f"; Box        : {box[0]:.3f} x {box[1]:.3f} x {box[2]:.3f} nm\n")
        f.write(f"; Generated by gen_sys.py  —  do not edit manually\n\n")

        # force-field parameters
        f.write('#include "forcefield.itp"\n\n')

        # molecule topologies
        for itp in itp_files:
            f.write(f'#include "{itp}"\n')
        f.write("\n")

        if if_water:
            # water (MARTINI W — always include the definition)
            f.write('; Standard MARTINI water bead (P4)\n')
            f.write('[ moleculetype ]\n; name  nrexcl\n  W  1\n\n')
            f.write('[ atoms ]\n; nr  type  resnr  resname  atom  cgnr  charge  mass\n')
            f.write('  1   P4    1    W      W    1    0.0   72.0\n\n')
        
        if if_antifreeze:
            f.write('; MARTINI antifreeze water bead (BP4)\n')
            f.write('[ moleculetype ]\n; name  nrexcl\n  WF  1\n\n')
            f.write('[ atoms ]\n; nr  type  resnr  resname  atom  cgnr  charge  mass\n')
            f.write('  1   BP4   1    WF     WF   1    0.0   72.0\n\n')

        # system block
        f.write("[ system ]\n")
        f.write("MARTINI hair surface simulation\n\n")

        # molecules block
        f.write("[ molecules ]\n")
        f.write("; molecule_name  count\n")
        for resname, count in mol_counts.items():
            if count > 0:
                f.write(f"  {resname:<12s}  {count}\n")
        f.write("\n")